### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by pym7857** [dkalshek/MeetingApp_demo#1]
- 영민
- [ ] 전체 DB구성 📌
- [ ] 채팅방 키워드로 왔다갔다 📌
- [x] State Management 공부(onChanged, Callback function, ListViewBuilder) 
- [ ] 비슷한 등급끼리 추천로직(피어슨 상관계수) 
- [x] Design Pattern (Provider/builder 패턴, ChangeNotifierProvider/Consumer 패턴) 공부 📢 [todoey](https://github.com/pym7857/todo_app-state_management_flutter)
- [ ] Design Pattern (Bloc패턴) 공부
- [ ] getX 공부
- [ ] 관리자 세션 
---
-  성원
- [x] geolocator 구현
- [x] SNS 로그인 수정
- [x] 어플 하나로 합치기
- [x] 사진 평가하는 위젯 구현(평가와 이미지를 연동하려면 DB와 연결필요)
- [x] 푸쉬알림 
- [ ] 인앱 결제 
- [ ] 아임포트 
- [x] git 사용법 익히기 
- [ ] UI 여러가지 모듈 알아두기 
- [ ] 마이페이지 
---
- 성렬
- [ ] UI 디자인 구성 
- [ ] 개인정보보호 관련 조항 검색
